name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get Lilypond
        uses: wei/wget@v1
        with:
          args: https://gitlab.com/api/v4/projects/lilypond%2Flilypond/packages/generic/lilypond/2.23.80/lilypond-2.23.80-linux-x86_64.tar.gz
      - name: Typeset score
        run: |
          tar -zxvf lilypond-2.23.80-linux-x86_64.tar.gz
          lilypond-2.23.80/bin/lilypond document.ly
