name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: fedora:37
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: dnf install -y lilypond bzip2 libxcrypt-compat
      - name: Get Lilypond
        uses: wei/wget@v1
        with:
          args: https://lilypond.org/download/binaries/linux-64/lilypond-2.22.2-1.linux-64.sh
      - name: Typeset score
        run: |
          sh lilypond-2.22.2-1.linux-64.sh --prefix $(pwd)/official-binaries
          official-binaries/bin/lilypond document.ly
